name: Build and test packages on windows2019
on:
  push:

jobs:

  build-and-test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: install micromamba
        uses: mamba-org/setup-micromamba@v1.8.1
        with:
          environment-file: environment.yaml
          cache-environment: true
          init-shell: none
          micromamba-version: '1.5.10-0'
